# NixOS configuration for lidafserver.
#
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running `nixos-help`).

{ config, pkgs, ... }:

{
  imports = [
    # Machine-specific, generated by `nixos-generate-config` and not
    # tracked in this repo (see README) — must exist alongside this
    # file for the rebuild to work.
    ./hardware-configuration.nix
  ];

  # ---------------------------------------------------------------------
  # Bootloader
  # ---------------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ---------------------------------------------------------------------
  # Networking / identity
  # ---------------------------------------------------------------------
  networking.hostName = "lidafserver";
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Only the Minecraft server port is exposed. RCON, if enabled later,
  # must stay off this list — it's for localhost only.
  networking.firewall.allowedTCPPorts = [ 25565 ];

  # ---------------------------------------------------------------------
  # Power management — this runs on a laptop repurposed as a server.
  # Closing the lid, on any power source, must never suspend it.
  # ---------------------------------------------------------------------
  services.logind = {
    lidSwitch = "ignore";
    lidSwitchExternalPower = "ignore";
    lidSwitchDocked = "ignore";
  };
  systemd.sleep.extraConfig = ''
    AllowSuspend=no
    AllowHibernation=no
  '';

  # Helps a lot when RAM is tight.
  zramSwap.enable = true;

  # ---------------------------------------------------------------------
  # Locale / time zone
  # ---------------------------------------------------------------------
  time.timeZone = "Asia/Riyadh";

  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "ar_SA.UTF-8";
    LC_IDENTIFICATION = "ar_SA.UTF-8";
    LC_MEASUREMENT = "ar_SA.UTF-8";
    LC_MONETARY = "ar_SA.UTF-8";
    LC_NAME = "ar_SA.UTF-8";
    LC_NUMERIC = "ar_SA.UTF-8";
    LC_PAPER = "ar_SA.UTF-8";
    LC_TELEPHONE = "ar_SA.UTF-8";
    LC_TIME = "ar_SA.UTF-8";
  };

  # Configure keymap in X11 (unused headless, but harmless to keep).
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # ---------------------------------------------------------------------
  # Remote access
  # ---------------------------------------------------------------------
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
  };

  # Human admin account. Password auth is off above, so this key is the
  # only way in — do not `nixos-rebuild switch` with this list still
  # empty or you will lock yourself out.
  users.users.lidafserver = {
    isNormalUser = true;
    description = "LIDAF";
    extraGroups = [ "networkmanager" "wheel" ];
    openssh.authorizedKeys.keys = [
      # TODO: paste the admin's public key here before first boot, e.g.
      # "ssh-ed25519 AAAA... comment"
    ];
    packages = with pkgs; [ ];
  };

  # ---------------------------------------------------------------------
  # Minecraft (NeoForge) server
  # ---------------------------------------------------------------------
  users.users.minecraft = {
    isSystemUser = true;
    group = "minecraft";
    home = "/var/lib/minecraft";
    createHome = true;
  };
  users.groups.minecraft = { };

  systemd.services.minecraft = {
    description = "Create Aeronautics Skybound server";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    path = [ pkgs.jdk21 pkgs.bash ];
    serviceConfig = {
      User = "minecraft";
      Group = "minecraft";
      WorkingDirectory = "/var/lib/minecraft";
      ExecStart = "${pkgs.bash}/bin/bash /var/lib/minecraft/run.sh nogui";
      Restart = "on-failure";
      RestartSec = "20s";
      # ~400 mods: first boot is slow, don't let systemd give up.
      TimeoutStartSec = "900";
      TimeoutStopSec = "180";
    };
  };

  nixpkgs.config.allowUnfree = true;

  # ---------------------------------------------------------------------
  # Packages
  # ---------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! Nano is also installed by default.
    wget
    unzip
    tmux
    jdk21
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
